"""empty message

Revision ID: 817be9c68528
Revises: 538e9aa3564b
Create Date: 2020-12-07 10:36:49.561331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817be9c68528'
down_revision = '538e9aa3564b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
